### ISSUE TITLE
Add a license to the repository

### ISSUE THREAD

**Issue by cbjuan** [AdrianoLusso/Aumentando-las-probabilidad-en-el-problema-de-Monty-Hall-con-computaci-n-cu-ntica#1]
I recently came across your project QiskitFallFest2023Hackaton_MontyHallProblemSimulationAndResolutionUsingQuantumComputing and I noticed that the repository github.com/AdrianoLusso/QiskitFallFest2023Hackaton_MontyHallProblemSimulationAndResolutionUsingQuantumComputing currently does not have a license specified.

Why Adding a License is Important?

As [GitHub documents](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)
>Public repositories on GitHub are often used to share open source software. For your repository to truly be open source, you'll need to license it so that others are free to use, change, and distribute the software.

Would be possible to add a valid license to this repository? Probably something really OpenSource such as the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0) would fit really well.

Thanks!

**Comment by AdrianoLusso** [comment]
Hi @cbjuan , you are totally right! I will add the OpenSource licence to this repository :D Thanks for your advice.

If you are interested in some of my current quantum software projects, i will post here a couple of links for you to check:

https://github.com/AdrianoLusso/QuantumComputing_for_AircraftLoadingOptimization
https://github.com/AdrianoLusso/QuantumComputing_for_JobReassignmentProblem

**Comment by cbjuan** [comment]
Thank you!
